spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      password: 3runner!23

  rabbitmq:
    host: localhost
    port: 5672
    username: 3runner
    password: 3runner!23

feign:
  client:
    url: localhost:8080