server:
  shutdown: graceful
  port: 8081


spring:
  profiles:
    active: local
  data:
    elasticsearch:
      repositories:
        enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-bookstore

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

#서비스 내려감
#cloud:
#  aws:
#    credentials:
#      access-key: f0a3fad864f3468293faa98da2807b67
#      secret-key: 4f48b4901ffe47b0b64cb9d909e87364
#    region:
#      static: KR1
#    s3:
#      endpoint: https://kr1-api-object-storage.nhncloudservice.com
#      bucket: nhnacademy-be6-3runner


springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /bookstore/docs/swagger


management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, conditions, prometheus
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true