spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        hbm2ddl:
          auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-bookstore

server:
  shutdown: graceful

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

cloud:
  aws:
    credentials:
      access-key: f0a3fad864f3468293faa98da2807b67
      secret-key: 4f48b4901ffe47b0b64cb9d909e87364
    region:
      static: KR1
    s3:
      endpoint: https://kr1-api-object-storage.nhncloudservice.com
      bucket: nhnacademy-be6-3runner


springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /bookstore/docs/swagger

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: 1234

redis:
  host: localhost
  port: 6379
  password: 1234

db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bookstore
  username: admin
  password: 1234
  initial-size: 10
  max-total: 10
  max-idle: 10
  min-idle: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, conditions, prometheus
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true