server:
  shutdown: graceful


eureka:
  instance:
    hostname: localhost

spring:
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: admin
      password: 1234

