spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:mysql://localhost:3307/coupon
        username: root
        password: 3runner!23
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
            initial-size: 5
            max-total: 20
            max-idle: 20
            min-idle: 5
            test-on-borrow: true
            validation-query: SELECT 1

    rabbitmq:
        host: localhost
        port: 5672
        username: 3runner
        password: 3runner!23

    data:
        redis:
            host: localhost
            port: 6379
            password: 3runner!23

eureka:
    client:
        fetch-registry: true
        service-url:
            defaultZone:
                http://admin:1234@localhost:8761/eureka
    instance:
        pref₩er-ip-address: true

feign:
    bookstore:
        url: localhost:8080
