server:
  port: 8084

spring:
  profiles:
    active: local

  application:
    name: 3runner-batch

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true

  batch:
    jdbc:
      initialize-schema: always

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

feign:
  coupon:
    url: localhost:8080