services:
#--------------------------------
#운영 Infra Container
#--------------------------------
  mysql-coupon:
    container_name: mysql-coupon
    image: mysql:8.0
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=coupon
      - MYSQL_ROOT_PASSWORD=3runner!23
    volumes:
      - ./envs/mysql/coupon/data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  mysql-bookstore:
    container_name: mysql-bookstore
    image: mysql:8.0
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=3runner!23
    volumes:
      - ./envs/mysql/bookstore/data:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 3runner!23
    volumes:
      - ./envs/infra/redis/redis_data:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - "15672:15672"  # RabbitMQ 관리 UI 포트
      - "5672:5672"    # AMQP 기본 포트
    environment:
      - RABBITMQ_DEFAULT_USER=3runner
      - RABBITMQ_DEFAULT_PASS=3runner!23
      - TZ=Asia/Seoul
    volumes:
      - ./envs/infra/rabbitmq/data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false         # 인증 비활성화 (개발용)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m       # 메모리 설정 (필요에 따라 조정)
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./envs/infra/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Seoul
    restart: always