services:
  app-coupon1:
    image: openjdk:21
    container_name: app-coupon1
    volumes:
      - ./script/coupon1/config:/config
      - ./script/coupon1/app:/app
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql-coupon
      - redis
      - rabbitmq
    command: >
      bash -c "java -jar /app/coupon.jar --spring.profiles.active=dev"
    network_mode: host
