services:
  app-batch:
    image: openjdk:21
    container_name: app-batch
    volumes:
      - ./script/batch/config:/config
      - ./script/batch/app:/app
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql-coupon
      - mysql-bookstore
      - redis
      - rabbitmq
    command: >
      bash -c "java -jar /app/batch.jar --spring.profiles.active=dev"
    network_mode: host