services:
  app-bookstore1:
    image: openjdk:21
    container_name: app-bookstore1
    volumes:
      - ./script/bookstore1/config:/config
      - ./script/bookstore1/app:/app
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql-bookstore
      - redis
      - rabbitmq
      - elasticsearch
      - kibana
    command: >
      bash -c "java -jar /app/bookstore.jar --spring.profiles.active=dev"
    network_mode: host
